version: "3"
services:
  hub: 
    image: selenium/hub:3.141.59
    ports:
      - "5555:4444"
  chrome:
    image: selenium/node-chrome:3.141.59
    shm_size: '512m'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59
    shm_size: '512m'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  searchmodule:
      image: bhagyan/selenium-docker:latest
      depends_on:
        - chrome
        - firefox
      environment:
        - host=hub
        - MODULE=searchmodule.xml
      volumes:
        - ./output/search-moduleoutput:/bhagya/test/test-output
  bookflightmodule:
      image: bhagyan/selenium-docker:latest
      depends_on:
        - chrome
        - firefox
      environment:
        - host=hub
        - Browser=firefox
        - MODULE=bookFlightModule.xml
      volumes:
        - ./output/bookFlight-moduleoutput:/bhagya/test/test-output
